CREATE FUNCTION dbo.TRIM (@string VARCHAR(MAX))
RETURNS VARCHAR(MAX)
AS BEGIN
	RETURN LTRIM(RTRIM(@string));
END;

-- GO


-- CREATE FUNCTION FIND_IN_SET(@value VARCHAR(MAX), @list VARCHAR(MAX), @delim VARCHAR(MAX))
--	RETURNS VARCHAR(MAX)
--	AS BEGIN
--		RETURN LTRIM(RTRIM(@value));
--	END;
