AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  SuggestExtensions: false
  # TODO: enable for tests.
  Exclude:
  - vendor/**/*
  - dev/**/*
  - test/**/*

# TODO: enable.
Gemspec/RequireMFA:
  Enabled: false

# TODO: enable.
Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/EndOfLine:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/LineLength:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true
  Exclude:
    - test/with_ar/all_agnostic_test.rb

# TODO: should we enable it? It's complaining about things like (1*2+3)
Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: true

# TODO: enable.
Metrics/AbcSize:
  Enabled: false

# TODO: enable.
Metrics/BlockLength:
  Enabled: false

# TODO: enable.
Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

# TODO: enable.
Metrics/CyclomaticComplexity:
  Enabled: false

# TODO: enable.
Metrics/PerceivedComplexity:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: true
  Exclude:
    - lib/arel_extensions/boolean_functions.rb

Naming/MethodName:
  Exclude:
    - lib/arel_extensions/boolean_functions.rb

# TODO: enable.
Naming/MethodParameterName:
  Enabled: false

Naming/FileName:
  Enabled: true

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# TODO: enable.
Style/Documentation:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/CommandLiteral:
  Enabled: true

Style/CommentAnnotation:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Style/Encoding:
  Enabled: true

# TODO: enable.
Style/GlobalVars:
  Enabled: false

# TODO: enable.
Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: true

Style/MultipleComparison:
  Enabled: true
  Exclude:
    - lib/arel_extensions/boolean_functions.rb

Style/NegatedIf:
  Enabled: false

Style/NumericLiterals:
  Enabled: true

Style/RedundantParentheses:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

# TODO: enable.
# We have some `... rescue nil` going on, let's keep it this way for now.
Style/RescueModifier:
  Enabled: false

# Even when conservative, this is unsafe.
# Style/StringConcatenation:
#   Enabled: true
#   Mode: 'conservative'

# This detects User.at[:id] + '1' as string concatenation, so never enable.
Style/StringConcatenation:
  Enabled: false

Style/StringLiterals:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/WordArray:
  Enabled: true

Style/YodaCondition:
  Enabled: false

# Performance cops have been transferred to rubocop-performance gem.
require: rubocop-performance

Performance/DoubleStartEndWith:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

Performance/StringReplacement:
  Enabled: true
