AllCops:
  DisabledByDefault: true
  Exclude:
  - "vendor/**/*"

Layout/EndOfLine:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/LineLength:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Metrics/BlockLength:
  Enabled: false

Naming/FileName:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/CommandLiteral:
  Enabled: true

Style/CommentAnnotation:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Style/Encoding:
  Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: true

Style/NegatedIf:
  Enabled: false

Style/StringLiterals:
  Enabled: true

# Performance cops have been transferred to rubocop-performance gem.
require: rubocop-performance

Performance/DoubleStartEndWith:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true
