AllCops:
  DisabledByDefault: true
  Exclude:
  - "vendor/**/*"

Layout/EndOfLine:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Naming/FileName:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/CommandLiteral:
  Enabled: true

Style/CommentAnnotation:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Style/Encoding:
  Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/StringLiterals:
  Enabled: true

# Performance cops have been transferred to rubocop-performance gem.
require: rubocop-performance

Performance/DoubleStartEndWith:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true
